apiVersion: v1

kind: Secret

metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  # A função `required` indica que MONGODB_URI é obrigatório.
  # Como este Workload é um Secret, o valor do MONGODB_URI não estará em nenhum YAML.
  # Este valor deverá ser passado através do terminal no momendo do deploy do Chart.
  MONGODB_URI: {{ required "`secret.dbUri` is required" .Values.secret.dbUri }}
