apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.pod.name }}
  ports:
    - name: http-service
      port: {{ default 80 .Values.service.port }}
      targetPort: http-container
