apiVersion: apps/v1

kind: Deployment

metadata:
  # Buscar no `values.yaml` o nome do Deployment.
  name: {{ .Values.deployment.name }}
  namespace:
    # Se não for passado um namespace pelo terminal, procura um namespace no
    # `values.yaml`.
    # Se não for encontrado um namespace no `values.yaml`, usar a função `default`.
    # A função `default` irá definir o namespace como "default".
    {{ default "default" .Values.deployment.namespace .Release.Namespace }}
spec:
  # Se não for encontrada a quantidade de réplicas, usar a função `default`.
  # A função `defualt` irá definir a quantidade de réplicas como 1.
  replicas: {{ default 1 .Values.deployment.replicas }}
  selector:
    matchLabels:
      # Buscar no `values.yaml` o nome do Pod.
      app: {{ .Values.pod.name }}
  template:
    metadata:
      labels:
        # Buscar no `values.yaml` o nome do Pod.
        app: {{ .Values.pod.name }}
    spec:
      containers:
        - name: shipmanager-container
          # Buscar no `Chart.yaml` a Tag da Image.
          # O Container Registry e o nome da Image geralmente é sempre o mesmo.
          image: sandb0/shipmanager-backend:v{{ .Chart.AppVersion }}
          ports:
            - name: http-container
              # Se não for encontrada a porta exposto do Container no `values.yaml`, usar a função `default`.
              # A função `defualt` irá definir a porta exposto do Container como 3000.
              containerPort: {{ default 3000 .Values.appPort }}
          # Converter uma variável em YAML.
          # O YAML é sensível à identação, por isso, identar 12 espaços.
          resources: {{- toYaml .Values.pod.resources | nindent 12 }}
          env:
            - name: DATABASE_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: shipmanager-backend-secret
                  key: MONGODB_URI
            - name: DATABASE_MONGODB_DBNAME
              # Se não for encontrado o nome do banco de dados no `values.yaml`, usar a função `default`.
              # A função `defualt` irá definir o nome do banco de dados como "ship_manager".
              value: {{ default "ship_manager" .Values.pod.env.dbName }}
