apiVersion: v1

kind: ConfigMap

metadata:
  name: {{ .Values.configMap.name }}
data:
  # A função `tpl` permite concatenar variáveis.
  config.js: |
    {{ tpl "const config = (() => ({'VUE_APP_BACKEND_BASE_URL': '{{ .Values.configMap.backendUri }}'}))();" . }}
