apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ default 1 .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.pod.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pod.name }}
    spec:
      volumes:
        - name: {{ .Values.volume.name }}
          configMap:
            name: {{ .Values.configMap.name }}
      containers:
        - name: shipmanager-frontend-container
          image: sandb0/shipmanager-frontend:v{{ .Chart.AppVersion }}
          ports:
            - name: http-container
              containerPort: {{ .Values.appPort }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: /usr/src/app/dist/configs
              readOnly: true
          resources: {{- toYaml .Values.pod.resources | nindent 12 }}
